### PR TITLE
Update to 3.30.1

### PR DESCRIPTION
**Pull request by mvainola**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
@mvainola we've just released the 3.30 runtime as well - it'd be good to upgrade to that as well.

**Comment by nedrichards** [comment]
bot, build

**Comment by mvainola** [comment]
Local build failed on libgee trying to install to /usr, not sure how to configure it.

**Comment by nedrichards** [comment]
that looks like https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/77 - in the short term you can either revert that change or set a config-opt in that module of `-DCMAKE_INSTALL_LIBDIR=lib`

EDIT: on a further look, maybe not.

**Comment by nedrichards** [comment]
Yeah, libgee should be looking at https://github.com/flathub/org.gnome.Contacts/blob/9dd67e6c33cc41391175f9275cf8d6826f310f2b/org.gnome.Contacts.yml#L42

**Comment by nedrichards** [comment]
Right, it seems that the new version of pkgconfig has changed the way it looks at environment variables.

**Comment by mvainola** [comment]
After reading the [upstream manifest](https://gitlab.gnome.org/GNOME/gnome-contacts/blob/master/data/flatpak/org.gnome.Contacts.json) I managed to build with the 3.30 runtime by moving girdir and typelibdir to libgee's make-install-args and removing liboauth and libgdata. Should I push those changes here or create a new PR for the runtime upgrade?

**Comment by nielsdg** [comment]
The PR looks good to me.

@mvainola: For me it's okay if you push those changes in this PR, as long as you keep it in a separate commit.

After those changes, this can be merged imo. Thanks guys :-)

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Will just check a build on all architectures and merge if green

**Comment by mvainola** [comment]
All green: [https://flathub.org/builds/#/builders/2/builds/5034](https://flathub.org/builds/#/builders/2/builds/5034)

**Comment by nielsdg** [comment]
Seems good!

**Pull request merged**
