### PR TITLE
Update to 3.32

### PR DESCRIPTION
**Pull request by mvainola**

### CODE REVIEW

**Comment by nedrichards** [comment]
I get:
> (gnome-contacts:3): Clutter-Gtk-ERROR **: 20:42:00.537: *** Unsupported backend.

When running this build on Endless OS.

**Comment by nedrichards** [comment]
That is caused by this bug upstream. https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/124

**Comment by mvainola** [comment]
The SDK issue seems to be fixed now. I tested this on both Wayland and X11 GNOME sessions on Fedora Silverblue 30. 

I also updated GOA and EDS. GOA 3.32 wasn't available previously and I couldn't access my Nextcloud contacts when mixing GOA and EDS versions .

**Comment by mvainola** [comment]
The Flathub build doesn't work for me though:

    $ flatpak install --user https://dl.flathub.org/build-repo/2032/org.gnome.Contacts.flatpakref
    $ flatpak run org.gnome.Contacts 
    gnome-contacts: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/lib/libgnome-desktop-3.so.17)

**Comment by jurf** [comment]
Works fine for me. Try updating your runtimes.

**Comment by nielsdg** [comment]
Apparently I didn't get a notification about this (or it somehow got archived. I'll try to review it after work or tomorrow

**Comment by monreal** [comment]
> Build [2889 successful](https://flathub.org/builds/#/builders/32/builds/2889)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/2762/org.gnome.Contacts.flatpakref
> ```

This test build seems to work fine for me

**Comment by nielsdg** [comment]
This is looking good. Thanks!

**Pull request merged**
